[package]
name = "toby"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide = { version = "0.17.0", features = ["macros"] }
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
regex = "1.12.2"
anyhow = "1.0.100"
chrono = "0.4.42"
